/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanilhaRouteImport } from './routes/planilha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as Pv2RouteImport } from './routes/pv2'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedDesejosRouteImport } from './routes/_authenticated/desejos'
import { Route as AuthenticatedFluxoRouteImport } from './routes/_authenticated/fluxo'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedMercadoRouteImport } from './routes/_authenticated/mercado'
import { Route as AuthenticatedParcelasRouteImport } from './routes/_authenticated/parcelas'
import { Route as AuthenticatedProdutividadeRouteImport } from './routes/_authenticated/produtividade'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanilhaRoute = PlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const Pv2Route = Pv2RouteImport.update({
  id: '/pv2',
  path: '/pv2',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesejosRoute = AuthenticatedDesejosRouteImport.update({
  id: '/desejos',
  path: '/desejos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoRoute = AuthenticatedFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMercadoRoute = AuthenticatedMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParcelasRoute = AuthenticatedParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutividadeRoute =
  AuthenticatedProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/guia': typeof GuiaRoute
  '/onboarding': typeof OnboardingRoute
  '/planilha': typeof PlanilhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv2': typeof Pv2Route
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRoute
  '/config': typeof AuthenticatedConfigRoute
  '/desejos': typeof AuthenticatedDesejosRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/guia': typeof GuiaRoute
  '/onboarding': typeof OnboardingRoute
  '/planilha': typeof PlanilhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv2': typeof Pv2Route
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRoute
  '/config': typeof AuthenticatedConfigRoute
  '/desejos': typeof AuthenticatedDesejosRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/guia': typeof GuiaRoute
  '/onboarding': typeof OnboardingRoute
  '/planilha': typeof PlanilhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv2': typeof Pv2Route
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/desejos': typeof AuthenticatedDesejosRoute
  '/_authenticated/fluxo': typeof AuthenticatedFluxoRoute
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/mercado': typeof AuthenticatedMercadoRoute
  '/_authenticated/parcelas': typeof AuthenticatedParcelasRoute
  '/_authenticated/produtividade': typeof AuthenticatedProdutividadeRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/cookies'
    | '/docs'
    | '/guia'
    | '/onboarding'
    | '/planilha'
    | '/privacidade'
    | '/pv2'
    | '/termos'
    | '/app'
    | '/config'
    | '/desejos'
    | '/fluxo'
    | '/gastos'
    | '/investimentos'
    | '/mercado'
    | '/parcelas'
    | '/produtividade'
    | '/tarefas'
    | '/auth/callback'
    | '/convite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/cookies'
    | '/docs'
    | '/guia'
    | '/onboarding'
    | '/planilha'
    | '/privacidade'
    | '/pv2'
    | '/termos'
    | '/app'
    | '/config'
    | '/desejos'
    | '/fluxo'
    | '/gastos'
    | '/investimentos'
    | '/mercado'
    | '/parcelas'
    | '/produtividade'
    | '/tarefas'
    | '/auth/callback'
    | '/convite/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/cookies'
    | '/docs'
    | '/guia'
    | '/onboarding'
    | '/planilha'
    | '/privacidade'
    | '/pv2'
    | '/termos'
    | '/_authenticated/app'
    | '/_authenticated/config'
    | '/_authenticated/desejos'
    | '/_authenticated/fluxo'
    | '/_authenticated/gastos'
    | '/_authenticated/investimentos'
    | '/_authenticated/mercado'
    | '/_authenticated/parcelas'
    | '/_authenticated/produtividade'
    | '/_authenticated/tarefas'
    | '/auth/callback'
    | '/convite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRoute
  GuiaRoute: typeof GuiaRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanilhaRoute: typeof PlanilhaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  Pv2Route: typeof Pv2Route
  TermosRoute: typeof TermosRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planilha': {
      id: '/planilha'
      path: '/planilha'
      fullPath: '/planilha'
      preLoaderRoute: typeof PlanilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pv2': {
      id: '/pv2'
      path: '/pv2'
      fullPath: '/pv2'
      preLoaderRoute: typeof Pv2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desejos': {
      id: '/_authenticated/desejos'
      path: '/desejos'
      fullPath: '/desejos'
      preLoaderRoute: typeof AuthenticatedDesejosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo': {
      id: '/_authenticated/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof AuthenticatedFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mercado': {
      id: '/_authenticated/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof AuthenticatedMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcelas': {
      id: '/_authenticated/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof AuthenticatedParcelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtividade': {
      id: '/_authenticated/produtividade'
      path: '/produtividade'
      fullPath: '/produtividade'
      preLoaderRoute: typeof AuthenticatedProdutividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDesejosRoute: typeof AuthenticatedDesejosRoute
  AuthenticatedFluxoRoute: typeof AuthenticatedFluxoRoute
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedMercadoRoute: typeof AuthenticatedMercadoRoute
  AuthenticatedParcelasRoute: typeof AuthenticatedParcelasRoute
  AuthenticatedProdutividadeRoute: typeof AuthenticatedProdutividadeRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDesejosRoute: AuthenticatedDesejosRoute,
  AuthenticatedFluxoRoute: AuthenticatedFluxoRoute,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedMercadoRoute: AuthenticatedMercadoRoute,
  AuthenticatedParcelasRoute: AuthenticatedParcelasRoute,
  AuthenticatedProdutividadeRoute: AuthenticatedProdutividadeRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRoute,
  GuiaRoute: GuiaRoute,
  OnboardingRoute: OnboardingRoute,
  PlanilhaRoute: PlanilhaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  Pv2Route: Pv2Route,
  TermosRoute: TermosRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
