/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedParcelasRouteImport } from './routes/_authenticated/parcelas'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedFluxoRouteImport } from './routes/_authenticated/fluxo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParcelasRoute = AuthenticatedParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoRoute = AuthenticatedFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fluxo': typeof AuthenticatedFluxoRoute
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/parcelas': typeof AuthenticatedParcelasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/fluxo' | '/gastos' | '/parcelas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/fluxo' | '/gastos' | '/parcelas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fluxo'
    | '/_authenticated/gastos'
    | '/_authenticated/parcelas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parcelas': {
      id: '/_authenticated/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof AuthenticatedParcelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo': {
      id: '/_authenticated/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof AuthenticatedFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFluxoRoute: typeof AuthenticatedFluxoRoute
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedParcelasRoute: typeof AuthenticatedParcelasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFluxoRoute: AuthenticatedFluxoRoute,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedParcelasRoute: AuthenticatedParcelasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
